# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 10493c953b24463c133b917186758de903d68d9a737490854218e7194dd0bb400253d094b6b3cdadf19e7150c5fdf01ababe1206abba468b84c849ed5bb57da6

test:
  secret_key_base: 3debb3dd00634df6e64734c65dc99c415e704fa8dab7e6ed3dbf0d4a4c2376d0fc7e3d8a3befaaecb06dceaa345014b19fd243144d30b0fdca38b716875541c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
